<?php

namespace PaymentPlugins\Stripe\Payments\Gateways;

use PaymentPlugins\Stripe\Assets\AssetsApi;
use PaymentPlugins\Stripe\Client\StripeClient;
use PaymentPlugins\Stripe\Traits\FeaturesTrait;

abstract class AbstractGateway extends \WC_Payment_Gateway {
	use FeaturesTrait;

	protected $payment_method_type;
	/**
	 * @var AssetsApi
	 */
	protected $assets;
	/**
	 * @var \StripeClient
	 */
	public $client;
	/**
	 * @var \WC_Stripe_Payment_Intent
	 */
	public $payment_controller;
	/**
	 * @var string
	 */
	protected $payment_method_id;

	public function __construct( \WC_Stripe_Payment_Intent $payment_controller, StripeClient $client, AssetsApi $assets ) {
		$this->payment_controller = $payment_controller;
		$this->payment_controller->set_payment_method( $this );
		$this->client = $client;
		$this->assets = $assets;
		$this->init_form_fields();
		$this->init_settings();
		$this->init_supports();
		$this->title       = $this->get_option( 'title_text' );
		$this->description = $this->get_option( 'description' );
	}

	public function initialize() {
	}

	/**
	 * @return array
	 * @since 4.0.0
	 */
	public function get_payment_method_data() {
		return [
			'paymentMethodType'     => $this->get_payment_method_type(),
			'elementOptions'        => $this->get_element_options(),
			'paymentElementOptions' => $this->get_payment_element_options()
		];
	}

	/**
	 * @return array
	 * @since 4.0.0
	 */
	public function get_checkout_script_handles() {
		return [];
	}

	/**
	 * @return array
	 * @since 4.0.0
	 */
	public function get_cart_script_handles() {
		return [];
	}

	/**
	 * @return array
	 * @since 4.0.0
	 */
	public function get_product_script_handles() {
		return [];
	}

	/**
	 * @return array
	 * @since 4.0.0
	 */
	public function get_express_checkout_script_handles() {
		return [];
	}

	/**
	 * @return array
	 * @since 4.0.0
	 */
	public function get_minicart_script_handles() {
		return [];
	}

	public function get_add_payment_method_script_handles() {
		return [];
	}

	public function is_express_checkout_enabled() {
		return in_array( 'express_checkout', (array) $this->get_option( 'payment_sections', [] ) );
	}

	/**
	 * @param $product
	 *
	 * @return bool
	 * @since 4.0.0
	 */
	public function is_product_section_enabled( $product ) {
		$settings = new \WC_Stripe_Product_Gateway_Option( $product, $this );

		return $settings->enabled();
	}

	public function is_cart_section_enabled() {
		return in_array( 'cart', (array) $this->get_option( 'payment_sections', array() ) );
	}

	public function is_minicart_section_enabled() {
		return in_array( 'mini_cart', (array) $this->get_option( 'payment_sections', array() ) );
	}

	public function get_tokens() {
		$tokens = parent::get_tokens();

		// TODO: Change the autogenerated stub
		return \PaymentPlugins\Stripe\Utilities\PaymentMethodUtils::sort_by_default( \PaymentPlugins\Stripe\Utilities\PaymentMethodUtils::filter_by_type( $tokens ) );
	}

	/**
	 * Returns true if the customer is using a saved payment method in the request.
	 * @return bool
	 */
	public function should_use_saved_payment_method() {
		$key = 'wc-' . $this->id . '-payment-token';

		//phpcs:disable WordPress.Security.NonceVerification.Missing
		return ! empty( $_POST[ $key ] ) && \wc_clean( \wp_unslash( $_POST[ $key ] ) ) !== 'new';
	}

	/**
	 * @param $value
	 *
	 * @return void
	 */
	public function set_payment_method_id( $value ) {
		$this->payment_method_id = $value;
	}

	/**
	 * Returns the payment method type for the payment method.
	 * @return string
	 */
	public function get_payment_method_type() {
		return $this->payment_method_type;
	}

	public function saved_payment_methods() {
		$tokens = $this->get_tokens();
		$html   = '<ul class="woocommerce-SavedPaymentMethods wc-saved-payment-methods" data-count="' . esc_attr( count( $tokens ) ) . '">';
		// The tokens are sorted so that the default method is first.
		// So we set $first to true so either the default method or first method is checked.
		$first = true;
		foreach ( $tokens as $token ) {
			$html  .= $this->get_saved_payment_method_option_html( $token, $first );
			$first = false;
		}
		$html .= $this->get_new_payment_method_option_html();
		$html .= '</ul>';
		echo apply_filters( 'wc_payment_gateway_form_saved_payment_methods_html', $html, $this );
		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	}

	/**
	 * @param \WC_Payment_Token_Stripe $token
	 *
	 * @return string
	 */
	public function get_saved_payment_method_option_html( $token, $checked = true ) {
		$icon_url = $this->assets->assets_url( $token->get_icon_file() );
		$classes  = 'woocommerce-SavedPaymentMethods-token wc-stripe-saved-method';
		if ( $checked ) {
			$classes .= ' selected';
		}
		$style = $checked ? '' : 'display:none;';
		$html  = sprintf( '<li class="%7$s" style="%8$s">
				<input id="wc-%1$s-payment-token-%2$s" type="radio" name="wc-%1$s-payment-token" value="%2$s" class="wc-stripe-saved-method__input woocommerce-SavedPaymentMethods-tokenInput" %4$s />
				<label for="wc-%1$s-payment-token-%2$s" class="wc-stripe-saved-method__label">
					<img src="%5$s" alt="%6$s" class="wc-stripe-saved-method__icon" />
					<span class="wc-stripe-saved-method__title">%3$s</span>
					%9$s
				</label>
			</li>', esc_attr( $this->id ), esc_attr( $token->get_id() ), esc_html( $token->get_display_name() ), checked( $checked, true, false ), esc_url( $icon_url ), esc_attr( $token->get_brand() ), esc_attr( $classes ), esc_attr( $style ), \count( $this->get_tokens() ) > 1 ? sprintf( '<a class="wc-stripe-saved-method__see-more" href="#">%1$s</a>', esc_html__( 'See more', 'woo-stripe-payment' ) ) : '' );

		return apply_filters( 'woocommerce_payment_gateway_get_saved_payment_method_option_html', $html, $token, $this );
	}

	public function get_new_payment_method_option_html() {
		$label = apply_filters( 'woocommerce_payment_gateway_get_new_payment_method_option_html_label', $this->new_method_label ? $this->new_method_label : __( 'Use a new payment method', 'woocommerce' ), $this );
		$html  = '';
		if ( ! empty( $this->get_tokens() ) ) {
			$html = sprintf( '<li class="woocommerce-SavedPaymentMethods-new">
				<input id="wc-%1$s-payment-token-new" type="radio" name="wc-%1$s-payment-token" value="new" class="wc-stripe-saved-method__input woocommerce-SavedPaymentMethods-tokenInput" />
				<label for="wc-%1$s-payment-token-new" class="wc-stripe-saved-method__label">
					<span class="wc-stripe-saved-method__plus"></span>
					<span class="wc-stripe-saved-method__title">%2$s</span>
				</label>
			</li>', esc_attr( $this->id ), esc_html( $label ) );
		}

		return apply_filters( 'woocommerce_payment_gateway_get_new_payment_method_option_html', $html, $this );
	}

	/**
	 * @param \WC_Order $order
	 *
	 * @return array
	 */
	public function process_zero_total_order( $order ) {
		if ( $this->should_use_saved_payment_method() ) {
			$this->payment_method_token = $this->get_payment_method_from_request();
		} else {
			$result = $this->payment_controller->process_setup_intent( $order, $this );
			if ( is_wp_error( $result ) || is_array( $result ) ) {
				return $result;
			}
			// $result is a succeeded setup intent.
			$this->save_payment_method( $result->payment_method->id, $order, $result->payment_method );
			$this->payment_method_token = $result->payment_method->id;
		}

		return $this->payment_controller->process_zero_total_order( $order, $this );
	}
}